name: Build Binaries

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "Windows"
          os: windows-latest
          build_output: './target/release/installer.msi'
          file_name: 'GeodeInstaller-win.msi'
        - name: "macOS"
          os: macos-latest
          build_output: './target/release/installer.app'
          file_name: 'GeodeInstaller-mac.app'
    
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@stable
        
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.config.name }}
        
    - name: Build
      run: |
        cargo install cargo-bundle
        cargo bundle --release
    
    - name: Move to output folder
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        mkdir out
        mv ${{ matrix.config.build_output }} ./out/${{ matrix.config.file_name }}
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.name }} Geode Installer
        path: ./out/${{ matrix.config.file_name }}
